routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Models\Galery;
use App\Models\Testimony;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//route web
Route::get('/', function () {
    $galeri = Galery::with('desainer','ulasan')
    ->leftjoin('kategori','kategori.id', '=', 'galeries.kategori_id')
    ->orderBy('galeries.created_at', 'desc')
    ->limit(3)
    ->get();
    return view('home', compact('galeri'));
});
Route::get('/kontak', function () {
    return view('web.kontak');
});
Route::get('/tentang', function () {
    return view('web.tentang');
});
Route::get('/testimoni', function () {
    $testimoni = Testimony::all();
    return view('web.testimoni', compact('testimoni'));
});


//route auth
Auth::routes();

//route middleware menu
Route::middleware('auth', 'admin')->group(function () {
    Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
        Route::get('/', [App\Http\Controllers\Admin\HomeController::class, 'index'])->name('admin');

        Route::get('/kategori', [App\Http\Controllers\Admin\KategoriController::class, 'index'])->name('kategori');
        Route::get('/kategori/create', [App\Http\Controllers\Admin\KategoriController::class, 'create'])->name('kategori.create');
        Route::get('/kategori/edit/{id}', [App\Http\Controllers\Admin\KategoriController::class, 'edit'])->name('kategori.edit');
        Route::post('/kategori/store', [App\Http\Controllers\Admin\KategoriController::class, 'store'])->name('kategori.store');
        Route::post('/kategori/update/{id}', [App\Http\Controllers\Admin\KategoriController::class, 'update'])->name('kategori.update');
        Route::post('/kategori/delete/{id}', [App\Http\Controllers\Admin\KategoriController::class, 'destroy'])->name('kategori.delete');
        Route::get('/kategori/datatable', [App\Http\Controllers\Admin\KategoriController::class, 'datatable'])->name('kategori.datatable');


        Route::get('/testimoni', [App\Http\Controllers\Admin\TestimoniController::class, 'index'])->name('testimoni');
        Route::get('/testimoni/create', [App\Http\Controllers\Admin\TestimoniController::class, 'create'])->name('testimoni.create');
        Route::get('/testimoni/edit/{id}', [App\Http\Controllers\Admin\TestimoniController::class, 'edit'])->name('testimoni.edit');
        Route::post('/testimoni/store', [App\Http\Controllers\Admin\TestimoniController::class, 'store'])->name('testimoni.store');
        Route::post('/testimoni/update/{id}', [App\Http\Controllers\Admin\TestimoniController::class, 'update'])->name('testimoni.update');
        Route::post('/testimoni/delete/{id}', [App\Http\Controllers\Admin\TestimoniController::class, 'destroy'])->name('testimoni.delete');
        Route::get('/testimoni/datatable', [App\Http\Controllers\Admin\TestimoniController::class, 'datatable'])->name('testimoni.datatable');

        //user management
        Route::get('/user-admin', [App\Http\Controllers\Admin\UserController::class, 'indexAdmin'])->name('user-admin');
        Route::get('/create', [App\Http\Controllers\Admin\UserController::class, 'create'])->name('create');
        Route::get('/edit/{id}', [App\Http\Controllers\Admin\UserController::class, 'edit'])->name('edit');
        Route::post('/store', [App\Http\Controllers\Admin\UserController::class, 'store'])->name('store');
        Route::post('/update/{id}', [App\Http\Controllers\Admin\UserController::class, 'update'])->name('update');
        Route::post('/delete/{id}', [App\Http\Controllers\Admin\UserController::class, 'destroy'])->name('delete');
        Route::get('/datatable', [App\Http\Controllers\Admin\UserController::class, 'datatableAdmin'])->name('datatable');

        Route::get('/desainer', [App\Http\Controllers\Admin\UserController::class, 'indexDesainer'])->name('desainer');
        Route::get('/desainer/create', [App\Http\Controllers\Admin\UserController::class, 'createDesainer'])->name('desainer.create');
        Route::get('/desainer/edit/{id}', [App\Http\Controllers\Admin\UserController::class, 'editDesainer'])->name('desainer.edit');
        Route::post('/desainer/store', [App\Http\Controllers\Admin\UserController::class, 'storeDesainer'])->name('desainer.store');
        Route::post('/desainer/update/{id}', [App\Http\Controllers\Admin\UserController::class, 'updateDesainer'])->name('desainer.update');
        Route::post('/desainer/delete/{id}', [App\Http\Controllers\Admin\UserController::class, 'destroyDesainer'])->name('desainer.delete');
        Route::get('/desainer/datatable', [App\Http\Controllers\Admin\UserController::class, 'datatableDesainer'])->name('desainer.datatable');

        Route::get('/customer', [App\Http\Controllers\Admin\UserController::class, 'indexCustomer'])->name('customer');
        Route::get('/customer/create', [App\Http\Controllers\Admin\UserController::class, 'createCustomer'])->name('customer.create');
        Route::get('/customer/edit/{id}', [App\Http\Controllers\Admin\UserController::class, 'editCustomer'])->name('customer.edit');
        Route::post('/customer/store', [App\Http\Controllers\Admin\UserController::class, 'storeCustomer'])->name('customer.store');
        Route::post('/customer/update/{id}', [App\Http\Controllers\Admin\UserController::class, 'updateCustomer'])->name('customer.update');
        Route::post('/customer/delete/{id}', [App\Http\Controllers\Admin\UserController::class, 'destroyCustomer'])->name('customer.delete');
        Route::get('/customer/datatable', [App\Http\Controllers\Admin\UserController::class, 'datatableCustomer'])->name('customer.datatable');

        Route::get('/agent', [App\Http\Controllers\Admin\UserController::class, 'indexAgent'])->name('agent');
        Route::get('/agent/create', [App\Http\Controllers\Admin\UserController::class, 'createAgent'])->name('agent.create');
        Route::get('/agent/edit/{id}', [App\Http\Controllers\Admin\UserController::class, 'editAgent'])->name('agent.edit');
        Route::post('/agent/store', [App\Http\Controllers\Admin\UserController::class, 'storeAgent'])->name('agent.store');
        Route::post('/agent/update/{id}', [App\Http\Controllers\Admin\UserController::class, 'updateAgent'])->name('agent.update');
        Route::post('/agent/delete/{id}', [App\Http\Controllers\Admin\UserController::class, 'destroyAgent'])->name('agent.delete');
        Route::get('/agent/datatable', [App\Http\Controllers\Admin\UserController::class, 'datatableAgent'])->name('agent.datatable');

        Route::get('/galeri', [App\Http\Controllers\Admin\GaleriController::class, 'index'])->name('galeri');


        Route::get('/pemesanan', [App\Http\Controllers\Admin\PemesananController::class, 'index'])->name('pemesanan');


        Route::get('/cash', [App\Http\Controllers\Admin\CashController::class, 'index'])->name('cash');
    });
});

Route::middleware('auth', 'desainer')->group(function () {
    Route::get('/karyaku', function () {
        return view('web.karyaku');
    });

    Route::group(['prefix' => 'desainer', 'as' => 'desainer.'], function () {
        Route::get('/', [App\Http\Controllers\Desainer\HomeController::class, 'index'])->name('desainer');


        Route::get('/profile', [App\Http\Controllers\Desainer\ProfileController::class, 'index'])->name('profile');


        Route::get('/galeri', [App\Http\Controllers\Desainer\GaleriController::class, 'index'])->name('galeri');
        Route::get('/galeri/datatable', [App\Http\Controllers\Desainer\GaleriController::class, 'datatable'])->name('galeri.datatable');
        Route::get('/galeri/create', [App\Http\Controllers\Desainer\GaleriController::class, 'create'])->name('galeri.create');
        Route::get('/galeri/edit/{id}', [App\Http\Controllers\Desainer\GaleriController::class, 'edit'])->name('galeri.edit');
        Route::post('/galeri/store', [App\Http\Controllers\Desainer\GaleriController::class, 'store'])->name('galeri.store');
        Route::post('/galeri/update/{id}', [App\Http\Controllers\Desainer\GaleriController::class, 'update'])->name('galeri.update');
        Route::post('/galeri/delete/{id}', [App\Http\Controllers\Desainer\GaleriController::class, 'destroy'])->name('galeri.delete');


        Route::get('/pemesanan', [App\Http\Controllers\Desainer\PemesananController::class, 'index'])->name('pemesanan');
        Route::get('/pemesanan/datatable', [App\Http\Controllers\Desainer\PemesananController::class, 'datatable'])->name('pemesanan.datatable');
        Route::get('/pemesanan/detail/{id}', [App\Http\Controllers\Desainer\PemesananController::class, 'getDetail'])->name('pemesanan.detail');
        Route::post('/pemesanan/update-status/{id}', [App\Http\Controllers\Desainer\PemesananController::class, 'updateStatus'])->name('pemesanan.update-status');
        Route::post('/pemesanan/upload-desain/{id}', [App\Http\Controllers\Desainer\PemesananController::class, 'uploadDesain'])->name('pemesanan.upload-desain');


        Route::get('/cash', [App\Http\Controllers\Desainer\CashController::class, 'index'])->name('cash');
    });
});

Route::get('/order', [App\Http\Controllers\OrderController::class, 'index']);
Route::get('/galeri', [App\Http\Controllers\GaleryController::class, 'index']);
Route::post('/ulasan/{id}', [App\Http\Controllers\OrderController::class, 'sendUlasan'])->name('ulasan');
Route::post('/storeRegister', [App\Http\Controllers\Auth\RegisterController::class, 'registrasi'])->name('storeRegistrasi');
Route::middleware('auth', 'customer')->group(function () {
    Route::get('/desainku', [App\Http\Controllers\OrderController::class, 'getOrder'])->name('desainku');

    Route::group(['prefix' => 'order', 'as' => 'order.'], function () {

app/Models/Desainer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Desainer extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id',
        'code',
        'nama_lengkap',
        'alamat',
        'no_hp',
        'keahlian',
        'img',
        'sumTask'
    ];

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }
}

app/Http/Controllers/Admin/GaleriController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class GaleriController extends Controller
{
    public function index()
    {
        return view('admin.galeri.index');
    }
}

app/Http/Controllers/Desainer/CashController.php
<?php

namespace App\Http\Controllers\Desainer;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CashController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('desainer.cash.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Desainer/GaleriController.php
<?php

namespace App\Http\Controllers\Desainer;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Galery;
use App\Models\Kategori;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Redirect;
use Yajra\DataTables\Facades\DataTables;

class GaleriController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('desainer.galeri.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $kategori = Kategori::get();
        return view('desainer.galeri.create', compact('kategori'));
    }

    public function edit(Request $request, $id)
    {
        $kategori = Kategori::get();
        $galery = Galery::where('id',$id)->first();
        return view('desainer.galeri.edit',['data'=>$galery, 'kategori'=>$kategori]);
    }

    public function store(Request $request)
    {
        $rules = [
            'kategori_id' => 'required',
            'caption' => 'required',
            'img' => 'required',
        ];
        $request->validate($rules);
        try {
            DB::beginTransaction();
            $imageUrl = $request->file('img');
            if ($imageUrl == null) {
                $img = $request->img;
            } else {
                $imageName = time().'.'.$request->file('img')->getClientOriginalExtension();
                $request->file('img')->move(public_path('/assets/dist/images'), $imageName);
                $img = '/assets/dist/images/'.$imageName;
            }
            $data = new Galery();

            $input = [
                'kategori_id' => $request->kategori_id,
                'desainer_id' => auth()->user()->id,
                'caption' => $request->caption,
                'img' => $img,
            ];
            $data->fill($input);
            $data->save();

            DB::commit();
            return Redirect::route('desainer.galeri')->with('success','Success');
        } catch (\Throwable $th) {
            DB::rollback();
            throw $th;
        }
    }

    public function update(Request $request,$id)
    {
        try {
            DB::beginTransaction();

            $data = Galery::where('id', $id)->first();
            $imageUrl = $request->file('img');
            if ($imageUrl == null) {
                $img =  $data->img;
            } else {
                $imageName = time().'.'.$request->file('img')->getClientOriginalExtension();
                $request->file('img')->move(public_path('/assets/dist/images'), $imageName);
                $img = '/assets/dist/images/'.$imageName;
            }
            Galery::where('id', $id)->update([
                'kategori_id' => $request->kategori_id,
                'caption' => $request->caption,
                'img' => $img,
            ]);

            DB::commit();
            return Redirect::route('desainer.galeri')->with('success','Edit Success');
        } catch (\Throwable $th) {
            DB::rollback();
            throw $th;
        }
    }

    public function destroy($id)
    {
        try {
            DB::beginTransaction();
            Galery::where('id',$id)->delete();
            DB::commit();
            return Redirect::route('desainer.galeri')->with('success','Hapus Success');
        } catch (\Throwable $th) {
            DB::rollback();
            throw $th;
        }
    }

    public function datatable()
    {
        return $data = DataTables::of(Galery::with('kategori')
        ->where('desainer_id', auth()->user()->id)
        ->orderBy('created_at', 'desc')
        ->get())
        ->make(true);
        $this->make($data);
    }
}

app/Http/Controllers/Desainer/HomeController.php
<?php

namespace App\Http\Controllers\Desainer;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('desainer.dashboard');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/desainer/galeri/create.blade.php
@extends('desainer.layouts.master')

@section('title') Create Galeri @endsection

@section('content')
<div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <!-- Default box -->
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Create Galeri</h3>

            <div class="card-tools">
              <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                <i class="fas fa-minus"></i></button>
              <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                <i class="fas fa-times"></i></button>
            </div>
          </div>
          <!-- form start -->
          <form role="form" action="{{route('desainer.galeri.store')}}" method="POST" id="quickForm" enctype="multipart/form-data">
            @csrf
            <div class="card-body">
                <div class="card-body">
                  <div class="form-group">
                    <label for="nama">Jenis Desain</label>
                    <select name="kategori_id" id="kategori_id" class="form-control">
                        @foreach ($kategori as $item)
                            <option value="{{$item->id}}">{{$item->name}}</option>
                        @endforeach
                    </select>
                  </div>
                  <div class="form-group">
                    <label for="nama">Image</label>
                    <input type="file" name="img" class="form-control">
                  </div>
                  <div class="form-group">
                    <label for="name">Captiom</label>
                    <textarea name="caption" class="form-control" id="name" placeholder="Enter Name" cols="30" rows="10"></textarea>
                  </div>
                  {{-- <div class="form-group mb-0">
                    <div class="custom-control custom-checkbox">
                      <input type="checkbox" name="terms" class="custom-control-input" id="exampleCheck1">
                      <label class="custom-control-label" for="exampleCheck1">I agree to the <a href="#">terms of service</a>.</label>
                    </div>
                  </div> --}}
                </div>
                <!-- /.card-body -->

            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
           </form>
          <!-- /.card-footer-->
        </div>
        <!-- /.card -->
      </div>
    </div>
  </div>
  @endsection

resources/views/desainer/galeri/edit.blade.php
@extends('desainer.layouts.master')

@section('title') Create Galeri @endsection

@section('content')
<div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <!-- Default box -->
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Create Galeri</h3>

            <div class="card-tools">
              <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                <i class="fas fa-minus"></i></button>
              <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                <i class="fas fa-times"></i></button>
            </div>
          </div>
          <!-- form start -->
          <form role="form" action="{{route('desainer.galeri.update', $data->id)}}" method="POST" id="quickForm" enctype="multipart/form-data">
            @csrf
            <div class="card-body">
                <div class="card-body">
                  <div class="form-group">
                    <label for="nama">Jenis Desain</label>
                    <select name="kategori_id" id="kategori_id" class="form-control">
                        @foreach ($kategori as $item)
                            <option value="{{$item->id}}" {{$item->id == $data->kategori_id?'selected':''}}>{{$item->name}}</option>
                        @endforeach
                    </select>
                  </div>
                  <div class="form-group">
                    <label for="nama">Image</label>
                    <img src="{{$data->img_asset}}" width="300" height="180">
                    <input type="file" name="img" class="form-control">
                  </div>
                  <div class="form-group">
                    <label for="name">Captiom</label>
                    <textarea name="caption" class="form-control" id="name" placeholder="Enter Name" cols="30" rows="10">{{$data->caption}}</textarea>
                  </div>
                  {{-- <div class="form-group mb-0">
                    <div class="custom-control custom-checkbox">
                      <input type="checkbox" name="terms" class="custom-control-input" id="exampleCheck1">
                      <label class="custom-control-label" for="exampleCheck1">I agree to the <a href="#">terms of service</a>.</label>
                    </div>
                  </div> --}}
                </div>
                <!-- /.card-body -->

            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
           </form>
          <!-- /.card-footer-->
        </div>
        <!-- /.card -->
      </div>
    </div>
  </div>
  @endsection

resources/views/desainer/galeri/index.blade.php
@extends('desainer.layouts.master')

@section('title') Galeri @endsection

@section('content')
<div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <!-- Default box -->
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Galeri</h3>

            <div class="card-tools">
              <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                <i class="fas fa-minus"></i></button>
              <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                <i class="fas fa-times"></i></button>
            </div>
          </div>
          <div class="card-body">
            <div class="row">
                <div class="col-12">
                    <a href="{{route('desainer.galeri.create')}}" class="btn btn-sm btn-primary btn-flat float-right"><span class="fas fa-plus"></span> Tambah Galeri </a>
                </div>
            </div>
            <table id="galeri" class="table table-bordered table-striped">
              <thead>
              <tr>
                <th>Jenis Desain</th>
                <th>Caption</th>
                <th>Img</th>
                <th>Created at</th>
                <th>Aksi</th>
              </tr>
              </thead>
              <tbody>

            </table>
          </div>
          <!-- /.card-body -->

          <!-- /.card-footer-->
        </div>
        <!-- /.card -->
      </div>
    </div>
  </div>
  @endsection

  @section('scripts')

  <script src="{{asset('plugins/datatables/jquery.dataTables.min.js')}}"></script>
  <script src="{{asset('plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
  <script src="{{asset('plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>
  <script src="{{asset('plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>
  <script>
    $("#galeri").DataTable({
      paging: true,
      searching: false,
      ordering: false,
      autoWidth: false,
      responsive: true,
      ajax: {
        "url":"{{ route('desainer.galeri.datatable') }}",
        "type":"GET",
      },
      columns : [
        {
            data : "kategori.name",
            name : "kategori.name"
        },
        {
            data : "caption",
            name : "caption",
        },
        {
            "data": "img_asset",
            render: function (data, type, row, meta) {
                return `<img src="${data}" width="80" height="50">`;
            }
        },
        {
            data : "created_at_formated",
            name : "created_at_formated",
        },
        {
            data : 'action',
            name : 'action',
        }
      ]
    });
  </script>

  @endsection