routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Models\Galery;
use App\Models\Testimony;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//route web
Route::get('/', function () {
    $galeri = Galery::with('desainer','ulasan')
    ->leftjoin('kategori','kategori.id', '=', 'galeries.kategori_id')
    ->orderBy('galeries.created_at', 'desc')
    ->limit(3)
    ->get();
    return view('home', compact('galeri'));
});
Route::get('/kontak', function () {
    return view('web.kontak');
});
Route::get('/tentang', function () {
    return view('web.tentang');
});
Route::get('/testimoni', function () {
    $testimoni = Testimony::all();
    return view('web.testimoni', compact('testimoni'));
});


//route auth
Auth::routes();

//route middleware menu
Route::middleware('auth', 'admin')->group(function () {
    Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
        Route::get('/', [App\Http\Controllers\Admin\HomeController::class, 'index'])->name('admin');

        Route::get('/kategori', [App\Http\Controllers\Admin\KategoriController::class, 'index'])->name('kategori');
        Route::get('/kategori/create', [App\Http\Controllers\Admin\KategoriController::class, 'create'])->name('kategori.create');
        Route::get('/kategori/edit/{id}', [App\Http\Controllers\Admin\KategoriController::class, 'edit'])->name('kategori.edit');
        Route::post('/kategori/store', [App\Http\Controllers\Admin\KategoriController::class, 'store'])->name('kategori.store');
        Route::post('/kategori/update/{id}', [App\Http\Controllers\Admin\KategoriController::class, 'update'])->name('kategori.update');
        Route::post('/kategori/delete/{id}', [App\Http\Controllers\Admin\KategoriController::class, 'destroy'])->name('kategori.delete');
        Route::get('/kategori/datatable', [App\Http\Controllers\Admin\KategoriController::class, 'datatable'])->name('kategori.datatable');


        Route::get('/testimoni', [App\Http\Controllers\Admin\TestimoniController::class, 'index'])->name('testimoni');
        Route::get('/testimoni/create', [App\Http\Controllers\Admin\TestimoniController::class, 'create'])->name('testimoni.create');
        Route::get('/testimoni/edit/{id}', [App\Http\Controllers\Admin\TestimoniController::class, 'edit'])->name('testimoni.edit');
        Route::post('/testimoni/store', [App\Http\Controllers\Admin\TestimoniController::class, 'store'])->name('testimoni.store');
        Route::post('/testimoni/update/{id}', [App\Http\Controllers\Admin\TestimoniController::class, 'update'])->name('testimoni.update');
        Route::post('/testimoni/delete/{id}', [App\Http\Controllers\Admin\TestimoniController::class, 'destroy'])->name('testimoni.delete');
        Route::get('/testimoni/datatable', [App\Http\Controllers\Admin\TestimoniController::class, 'datatable'])->name('testimoni.datatable');

        //user management
        Route::get('/user-admin', [App\Http\Controllers\Admin\UserController::class, 'indexAdmin'])->name('user-admin');
        Route::get('/create', [App\Http\Controllers\Admin\UserController::class, 'create'])->name('create');
        Route::get('/edit/{id}', [App\Http\Controllers\Admin\UserController::class, 'edit'])->name('edit');
        Route::post('/store', [App\Http\Controllers\Admin\UserController::class, 'store'])->name('store');
        Route::post('/update/{id}', [App\Http\Controllers\Admin\UserController::class, 'update'])->name('update');
        Route::post('/delete/{id}', [App\Http\Controllers\Admin\UserController::class, 'destroy'])->name('delete');
        Route::get('/datatable', [App\Http\Controllers\Admin\UserController::class, 'datatableAdmin'])->name('datatable');

        Route::get('/desainer', [App\Http\Controllers\Admin\UserController::class, 'indexDesainer'])->name('desainer');
        Route::get('/desainer/create', [App\Http\Controllers\Admin\UserController::class, 'createDesainer'])->name('desainer.create');
        Route::get('/desainer/edit/{id}', [App\Http\Controllers\Admin\UserController::class, 'editDesainer'])->name('desainer.edit');
        Route::post('/desainer/store', [App\Http\Controllers\Admin\UserController::class, 'storeDesainer'])->name('desainer.store');
        Route::post('/desainer/update/{id}', [App\Http\Controllers\Admin\UserController::class, 'updateDesainer'])->name('desainer.update');
        Route::post('/desainer/delete/{id}', [App\Http\Controllers\Admin\UserController::class, 'destroyDesainer'])->name('desainer.delete');
        Route::get('/desainer/datatable', [App\Http\Controllers\Admin\UserController::class, 'datatableDesainer'])->name('desainer.datatable');

        Route::get('/customer', [App\Http\Controllers\Admin\UserController::class, 'indexCustomer'])->name('customer');
        Route::get('/customer/create', [App\Http\Controllers\Admin\UserController::class, 'createCustomer'])->name('customer.create');
        Route::get('/customer/edit/{id}', [App\Http\Controllers\Admin\UserController::class, 'editCustomer'])->name('customer.edit');
        Route::post('/customer/store', [App\Http\Controllers\Admin\UserController::class, 'storeCustomer'])->name('customer.store');
        Route::post('/customer/update/{id}', [App\Http\Controllers\Admin\UserController::class, 'updateCustomer'])->name('customer.update');
        Route::post('/customer/delete/{id}', [App\Http\Controllers\Admin\UserController::class, 'destroyCustomer'])->name('customer.delete');
        Route::get('/customer/datatable', [App\Http\Controllers\Admin\UserController::class, 'datatableCustomer'])->name('customer.datatable');

        Route::get('/agent', [App\Http\Controllers\Admin\UserController::class, 'indexAgent'])->name('agent');
        Route::get('/agent/create', [App\Http\Controllers\Admin\UserController::class, 'createAgent'])->name('agent.create');
        Route::get('/agent/edit/{id}', [App\Http\Controllers\Admin\UserController::class, 'editAgent'])->name('agent.edit');
        Route::post('/agent/store', [App\Http\Controllers\Admin\UserController::class, 'storeAgent'])->name('agent.store');
        Route::post('/agent/update/{id}', [App\Http\Controllers\Admin\UserController::class, 'updateAgent'])->name('agent.update');
        Route::post('/agent/delete/{id}', [App\Http\Controllers\Admin\UserController::class, 'destroyAgent'])->name('agent.delete');
        Route::get('/agent/datatable', [App\Http\Controllers\Admin\UserController::class, 'datatableAgent'])->name('agent.datatable');

        Route::get('/galeri', [App\Http\Controllers\Admin\GaleriController::class, 'index'])->name('galeri');


        Route::get('/pemesanan', [App\Http\Controllers\Admin\PemesananController::class, 'index'])->name('pemesanan');


        Route::get('/cash', [App\Http\Controllers\Admin\CashController::class, 'index'])->name('cash');
    });
});

Route::middleware('auth', 'desainer')->group(function () {
    Route::get('/karyaku', function () {
        return view('web.karyaku');
    });

    Route::group(['prefix' => 'desainer', 'as' => 'desainer.'], function () {
        Route::get('/', [App\Http\Controllers\Desainer\HomeController::class, 'index'])->name('desainer');


        Route::get('/profile', [App\Http\Controllers\Desainer\ProfileController::class, 'index'])->name('profile');


        Route::get('/galeri', [App\Http\Controllers\Desainer\GaleriController::class, 'index'])->name('galeri');
        Route::get('/galeri/datatable', [App\Http\Controllers\Desainer\GaleriController::class, 'datatable'])->name('galeri.datatable');
        Route::get('/galeri/create', [App\Http\Controllers\Desainer\GaleriController::class, 'create'])->name('galeri.create');
        Route::get('/galeri/edit/{id}', [App\Http\Controllers\Desainer\GaleriController::class, 'edit'])->name('galeri.edit');
        Route::post('/galeri/store', [App\Http\Controllers\Desainer\GaleriController::class, 'store'])->name('galeri.store');
        Route::post('/galeri/update/{id}', [App\Http\Controllers\Desainer\GaleriController::class, 'update'])->name('galeri.update');
        Route::post('/galeri/delete/{id}', [App\Http\Controllers\Desainer\GaleriController::class, 'destroy'])->name('galeri.delete');


        Route::get('/pemesanan', [App\Http\Controllers\Desainer\PemesananController::class, 'index'])->name('pemesanan');
        Route::get('/pemesanan/datatable', [App\Http\Controllers\Desainer\PemesananController::class, 'datatable'])->name('pemesanan.datatable');
        Route::get('/pemesanan/detail/{id}', [App\Http\Controllers\Desainer\PemesananController::class, 'getDetail'])->name('pemesanan.detail');
        Route::post('/pemesanan/update-status/{id}', [App\Http\Controllers\Desainer\PemesananController::class, 'updateStatus'])->name('pemesanan.update-status');
        Route::post('/pemesanan/upload-desain/{id}', [App\Http\Controllers\Desainer\PemesananController::class, 'uploadDesain'])->name('pemesanan.upload-desain');


        Route::get('/cash', [App\Http\Controllers\Desainer\CashController::class, 'index'])->name('cash');
    });
});

Route::get('/order', [App\Http\Controllers\OrderController::class, 'index']);
Route::get('/galeri', [App\Http\Controllers\GaleryController::class, 'index']);
Route::post('/ulasan/{id}', [App\Http\Controllers\OrderController::class, 'sendUlasan'])->name('ulasan');
Route::post('/storeRegister', [App\Http\Controllers\Auth\RegisterController::class, 'registrasi'])->name('storeRegistrasi');
Route::middleware('auth', 'customer')->group(function () {
    Route::get('/desainku', [App\Http\Controllers\OrderController::class, 'getOrder'])->name('desainku');

    Route::group(['prefix' => 'order', 'as' => 'order.'], function () {

app/Models/Customer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id',
        'name',
        'phone_number',
        'address',
        'email',
        'img',
    ];

    protected $dates = ['created_at'];

}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'role',
        'password',
    ];
    protected $dates = ['created_at'];

    protected $appends =['action','created_at_formated'];
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getActionAttribute()
    {
        return view('admin.user.admin.components.action',['data'=>$this])->render();
    }

    public function getCreatedAtFormatedAttribute()
    {
        return $this->created_at->format('d-m-Y H:i:s');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','role'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

resources/views/admin/user/customer/create.blade.php
@extends('admin.layouts.master')

@section('title') Create customer @endsection

@section('content')
<div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <!-- Default box -->
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Create customer</h3>

            <div class="card-tools">
              <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                <i class="fas fa-minus"></i></button>
              <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                <i class="fas fa-times"></i></button>
            </div>
          </div>
          <!-- form start -->
          <form role="form" action="{{route('admin.customer.store')}}" method="POST" id="quickForm">
            @csrf
            <div class="card-body">
                <div class="card-body">
                  <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" name="name" class="form-control" id="name" placeholder="Enter Name">
                  </div>
                  <div class="form-group">
                    <label for="exampleInputEmail1">Email address</label>
                    <input type="email" name="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
                  </div>
                  <div class="form-group">
                    <label for="exampleInputPassword1">Password</label>
                    <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
                  </div>
                  {{-- <div class="form-group mb-0">
                    <div class="custom-control custom-checkbox">
                      <input type="checkbox" name="terms" class="custom-control-input" id="exampleCheck1">
                      <label class="custom-control-label" for="exampleCheck1">I agree to the <a href="#">terms of service</a>.</label>
                    </div>
                  </div> --}}
                </div>
                <!-- /.card-body -->

            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
           </form>
          <!-- /.card-footer-->
        </div>
        <!-- /.card -->
      </div>
    </div>
  </div>
  @endsection
  @section('scripts')
  <script type="text/javascript">
    $(document).ready(function () {
      $.validator.setDefaults({
        submitHandler: function () {

        }
      });
      $('#quickForm').validate({
        rules: {
          name: {
            required: true,
          },
          email: {
            required: true,
            email: true,
          },
          password: {
            required: true,
            minlength: 6
          },
        },
        messages: {
          email: {
            required: "Please enter a email address",
            email: "Please enter a vaild email address"
          },
          password: {
            required: "Please provide a password",
            minlength: "Your password must be at least 5 characters long"
          },
          name: "Please enter a name"
        },
        errorElement: 'span',
        errorPlacement: function (error, element) {
          error.addClass('invalid-feedback');
          element.closest('.form-group').append(error);
        },
        highlight: function (element, errorClass, validClass) {
          $(element).addClass('is-invalid');
        },
        unhighlight: function (element, errorClass, validClass) {
          $(element).removeClass('is-invalid');
        }
      });
    });
    </script>
  @endsection

resources/views/admin/user/customer/edit.blade.php
@extends('admin.layouts.master')

@section('title') Edit customer @endsection

@section('content')
<div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <!-- Default box -->
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Edit customer</h3>

            <div class="card-tools">
              <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                <i class="fas fa-minus"></i></button>
              <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                <i class="fas fa-times"></i></button>
            </div>
          </div>
          <!-- form start -->
          <form role="form" action="{{route('admin.customer.update',$data->id)}}" method="POST" id="quickForm">
            @csrf
            <div class="card-body">
                <div class="card-body">
                  <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" name="name" value="{{$data->name}}" class="form-control" id="name" placeholder="Enter Name">
                  </div>
                  <div class="form-group">
                    <label for="exampleInputEmail1">Email address</label>
                    <input type="email" name="email" value="{{$data->email}}" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
                  </div>
                  {{-- <div class="form-group mb-0">
                    <div class="custom-control custom-checkbox">
                      <input type="checkbox" name="terms" class="custom-control-input" id="exampleCheck1">
                      <label class="custom-control-label" for="exampleCheck1">I agree to the <a href="#">terms of service</a>.</label>
                    </div>
                  </div> --}}
                </div>
                <!-- /.card-body -->

            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Update</button>
            </div>
           </form>
          <!-- /.card-footer-->
        </div>
        <!-- /.card -->
      </div>
    </div>
  </div>
  @endsection
  @section('scripts')
  <script type="text/javascript">
    $(document).ready(function () {
      $.validator.setDefaults({
        submitHandler: function () {

        }
      });
      $('#quickForm').validate({
        rules: {
          name: {
            required: true,
          },
          email: {
            required: true,
            email: true,
          },
          password: {
            required: true,
            minlength: 6
          },
        },
        messages: {
          email: {
            required: "Please enter a email address",
            email: "Please enter a vaild email address"
          },
          password: {
            required: "Please provide a password",
            minlength: "Your password must be at least 5 characters long"
          },
          name: "Please enter a name"
        },
        errorElement: 'span',
        errorPlacement: function (error, element) {
          error.addClass('invalid-feedback');
          element.closest('.form-group').append(error);
        },
        highlight: function (element, errorClass, validClass) {
          $(element).addClass('is-invalid');
        },
        unhighlight: function (element, errorClass, validClass) {
          $(element).removeClass('is-invalid');
        }
      });
    });
    </script>
  @endsection

resources/views/admin/user/customer/index.blade.php
@extends('admin.layouts.master')

@section('title') Customer User @endsection

@section('content')
<div class="container-fluid">
    <div class="row">
      <div class="col-12">

        <!-- Default box -->
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Customer User</h3>

            <div class="card-tools">
              <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                <i class="fas fa-minus"></i></button>
              <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                <i class="fas fa-times"></i></button>
            </div>
          </div>
          <div class="card-body">
            <div class="row">
                <div class="col-12">
                <a href="{{route('admin.customer.create')}}" class="btn btn-sm btn-primary btn-flat float-right"><span class="fas fa-plus"></span> Tambah Customer </a>
                </div>
            </div>
            <table id="customer" class="table table-bordered table-striped">
              <thead>
              <tr>
                <th>Nama</th>
                <th>Email</th>
                <th>Created at</th>
                <th>Aksi</th>
              </tr>
              </thead>
              <tbody>

            </table>
          </div>
          <!-- /.card-body -->

          <!-- /.card-footer-->
        </div>
        <!-- /.card -->
      </div>
    </div>
  </div>
  @endsection

  @section('scripts')

  <script src="{{asset('plugins/datatables/jquery.dataTables.min.js')}}"></script>
  <script src="{{asset('plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
  <script src="{{asset('plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>
  <script src="{{asset('plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>
  <script>
    $("#customer").DataTable({
      paging: true,
      searching: false,
      responsive: true,
      ajax: {
        "url":"{{ route('admin.customer.datatable') }}",
        "type":"GET",
      },
      columns : [
        {
            data : "name",
            name : "name"
        },
        {
            data : "email",
            name : "email"
        },
        {
            data : "created_at_formated",
            name : "created_at_formated",
        },
        {
            data : "action",
            name : "action",
        }
      ]
    });
  </script>

  @endsection